CREATE TABLE cursos(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    periodo VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_periodo CHECK ( periodo IN ('MATUTINO', 'VESPERTINO', 'NOTURNO', 'INTEGRAL'))
);